id: A0C1FF98A
base_file: f15A1.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:12:51.132135
  last_modified_at: 2022-06-05 20:12:51.132161
