id: A0C1FF98A
base_file: fFC65.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:12:51.174513
  last_modified_at: 2022-06-05 20:12:51.174517
