id: A0C1FF98A
base_file: f543E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:12:51.158974
  last_modified_at: 2022-06-05 20:12:51.158979
