id: A0C1FF98A
base_file: fEEEB.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:12:51.169685
  last_modified_at: 2022-06-05 20:12:51.169688
